# .github/workflows/frontend-ci-cd.yml
name: Frontend CI/CD (GitHub Pages)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          # CORREÇÃO: Adiciona --base=/CoreERP/ ao comando de build
          # Isso é o que resolve o erro 404 no GitHub Pages
          npm run build -- --base=/CoreERP/ 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # É mais seguro usar o token padrão, que tem as permissões necessárias
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist